# Generated by Django 5.1.1 on 2024-11-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='chat_type',
            field=models.CharField(choices=[('chatapp', 'ChatApp'), ('chatapp_plus', 'ChatApp Plus')], default='chatapp', max_length=20),
        ),
    ]
