# Generated by Django 5.2.1 on 2025-05-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='api_endpoint',
            field=models.CharField(blank=True, help_text='API endpoint for LangGraph agents', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='assistant',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='agent',
            name='chat_type',
            field=models.CharField(choices=[('chatapp', 'ChatApp'), ('chatapp_plus', 'ChatApp Plus'), ('langgraph', 'LangGraph Agent')], default='chatapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='vector_store',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
