# Generated by Django 5.2.1 on 2025-06-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_api_endpoint_agent_featured_agent_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='chat_type',
            field=models.CharField(choices=[('chatapp', 'ChatApp'), ('chatapp_plus', 'ChatApp Plus'), ('langgraph', 'LangGraph Agent'), ('custom', 'Custom Application')], default='chatapp', max_length=20),
        ),
    ]
