# Generated by Django 5.2.1 on 2025-06-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agent_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image_filename',
            field=models.CharField(blank=True, help_text='Custom image filename (without .jpg extension). If blank, uses agent name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='api_endpoint',
            field=models.CharField(blank=True, help_text='API endpoint for custom agents; agents under the LangGraph app do not need this explicitly', max_length=255),
        ),
    ]
