# Generated by Django 5.2.1 on 2025-06-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_image_filename_alter_agent_api_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='example_message',
            field=models.CharField(blank=True, help_text='Example message to show as placeholder in chat input. If empty, uses generic placeholder.', max_length=255),
        ),
    ]
