# Generated by Django 5.2.1 on 2025-06-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_jobs_found', models.IntegerField(default=0)),
                ('total_top_picks', models.IntegerField(default=0)),
                ('total_pages_processed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description_summary', models.TextField()),
                ('apply_url', models.URLField(max_length=500)),
                ('is_top_pick', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='IM_scanner.scanrun')),
            ],
            options={
                'ordering': ['-is_top_pick', '-created_at'],
                'indexes': [models.Index(fields=['apply_url'], name='IM_scanner__apply_u_1c297a_idx'), models.Index(fields=['scan_run', 'is_top_pick'], name='IM_scanner__scan_ru_4f80f0_idx'), models.Index(fields=['job_title'], name='IM_scanner__job_tit_280d0d_idx'), models.Index(fields=['company'], name='IM_scanner__company_894dcd_idx')],
            },
        ),
    ]
