# Generated by Django 5.2.1 on 2025-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IM_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(max_length=300),
        ),
    ]
